ALTER TABLE metric_history ADD COLUMN sample_count INTEGER NOT NULL DEFAULT 1 CHECK(sample_count > 0);
ALTER TABLE metric_history ADD COLUMN first_timestamp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE metric_history ADD COLUMN last_timestamp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE metric_history ADD COLUMN cpu_min REAL;
ALTER TABLE metric_history ADD COLUMN cpu_max REAL;
ALTER TABLE metric_history ADD COLUMN mem_used_max INTEGER;
ALTER TABLE metric_history ADD COLUMN memory_avg REAL;
ALTER TABLE metric_history ADD COLUMN memory_min REAL;
ALTER TABLE metric_history ADD COLUMN disk_avg REAL;
ALTER TABLE metric_history ADD COLUMN disk_min REAL;
ALTER TABLE metric_history ADD COLUMN net_in_avg REAL;
ALTER TABLE metric_history ADD COLUMN net_in_min REAL;
ALTER TABLE metric_history ADD COLUMN net_out_avg REAL;
ALTER TABLE metric_history ADD COLUMN net_out_min REAL;
