version: 2

updates:
  - package-ecosystem: cargo
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-rust:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /agent
    schedule:
      interval: weekly
    groups:
      agent-rust:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      web:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
